[project]
name = "sqlmat"
version = "0.1.0"
authors = [
    { name = "Marcin Gryszko", email = "mgryszko@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "duckdb",
    "jinja2",
]

[dependency-groups]
dev = [
    "pytest",
    "python-dotenv",
    "redshift-connector",
    "ruff",
]

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["tests"]

[tool.ruff]
line-length = 140
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "PT"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
